[package]
name = "aoc"
version = "0.1.0"
authors = ["Wojtek <woj.lass@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "1"
path = "src/tasks/1.rs"
